// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cryptopages": jwt Resource Client
//
// Command:
// $ goagen
// --design=github.com/tutley/cryptopages/design
// --out=$(GOPATH)/src/github.com/tutley/cryptopages
// --regen=true
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// SigninJWTPath computes a request path to the signin action of jwt.
func SigninJWTPath() string {

	return fmt.Sprintf("/api/jwt/signin")
}

// Creates a valid JWT
func (c *Client) SigninJWT(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewSigninJWTRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewSigninJWTRequest create the request corresponding to the signin action endpoint of the jwt resource.
func (c *Client) NewSigninJWTRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.SigninBasicAuthSigner != nil {
		if err := c.SigninBasicAuthSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
