// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cryptopages": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/tutley/cryptopages/design
// --out=$(GOPATH)/src/github.com/tutley/cryptopages
// --regen=true
// --version=v1.3.1

package test
